apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devboard
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Akash08-Git/devboard.git
    targetRevision: gitops
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: devboard

  syncPolicy:
    automated:
      prune: true      # delete resources removed from Git
      selfHeal: true   # revert manual drift back to Git
    syncOptions:
      - CreateNamespace=true
